name: Update Docc documentation
on:
  push:
    branches:
      - master
jobs:
    update-api-documentation:
        runs-on: macos-latest
        steps:
            - name: generate doc files
              run: xcodebuild docbuild -scheme ApiVideoPlayerAnalytics -derivedDataPath ../api.video-ios-player-analytics/api.video-ios-player-analytics-build -destination 'platform=iOS Simulator,name=iPhone 12'
            - name: create docs folder
              run: mkdir ../api.video-ios-player-analytics/Docs
            - name: process docarchive
              run: $(xcrun --find docc) process-archive \
              transform-for-static-hosting ../api.video-ios-player-analytics/api.video-ios-player-analytics-build/Build/Products/Debug-iphonesimulator/ApiVideoPlayerAnalytics.doccarchive \
              --output-path ../api.video-ios-player-analytics/Docs \
              --hosting-base-path https://apivideo.github.io/api.video-ios-player-analytics
            - name: Deploy documentation to Github Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BRANCH: gh-pages
                FOLDER: Docs
        
    

